### ISSUE TITLE
Server - Crie um servidor de configuração Spring

### ISSUE THREAD

**Issue by victtorfreitas** [victtorfreitas/micro-service#8]
Criar um servidor para armazenar as configurações importantes dos micros serviços

**Comment by victtorfreitas** [comment]
As configurações:

```
spring:
  datasource:
    password: root
    username: xxxxx
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
```
Foram movidas para o arquivo `c:/microservices-repo/fornecedor.yml`
