### ISSUE TITLE
Fornecedor - Remove configurações de banco de dados

### ISSUE THREAD

**Issue by victtorfreitas** [victtorfreitas/micro-service#9]
Remove do projeto as configurações 

```
spring:
  datasource:
    password: 
    username: 
    url:
    driver-class-name:
```
Pois estas configurações serão gerenciados pelo servidor **server-config**
